version: "3.8"
services:
    nestjs:
        image: node:14.17.6
        volumes:
            - ./:/app:z
        environment:
            NODE_ENV: "development"
        working_dir: /app
        command: sh -c 'yarn && yarn start:dev'
        ports:
            - 3000:3000
        networks:
            - nestjs_network
networks:
    nestjs_network:
        name: "nestjs_backend_network"
